version: '3.7'

services:
  mysql:
    container_name: api-mysql
    image: api-mysql
    build:
      context: .
      dockerfile: ./dockerfile.db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    networks:
      - api-network
    ports:
      - 3306:3306
  app:
    depends_on:
      - mysql
    container_name: api-app
    image: api-app
    build:
      context: .
      dockerfile: ./dockerfile.api
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
    networks:
      - api-network

networks:
  api-network: